- name: Update apt cache
  apt: update_cache=yes cache_valid_time=36000
  when: ansible_os_family == 'Debian'
  changed_when: false

- name: Ensure sefacl and facl binaries are installed (Debian)
  package:
    name: acl
    state: present

- name: Ensure www-directory exists and has correct access-rights
  become: true
  file:
    path: "{{ d_root }}"
    owner: "{{ php_fpm_pool_user }}"
    group: "{{ lookup('pipe', 'whoami') }}"
    mode: "u=rwx,g=rwx,o=r--"
    state: directory
    recurse: true
  no_log: true
  
- name: Set documentroots current ACLs
  become: true
  acl:
    path: "{{ d_root }}"
    entity: "{{ lookup('pipe', 'whoami') }}"
    etype: user
    state: present
    permissions: rwx
    recursive: true
  no_log: true
    
- name: Set documentroots current ACLs
  become: true
  acl:
    path: "{{ d_root }}"
    entity: "{{ php_fpm_pool_user }}"
    etype: user
    state: present
    permissions: rwx
    recursive: true
  no_log: true
  
- name: Set documentroots default ACLs for logged in user
  become: true
  acl:
    path: "{{ d_root }}"
    entity: "{{ lookup('pipe', 'whoami') }}"
    etype: user
    state: present
    permissions: rwx
    default: true
    recursive: true
  no_log: true
    
- name: Set documentroots default ACLs for PHP-FPM user
  become: true
  acl:
    path: "{{ d_root }}"
    entity: "{{ php_fpm_pool_user }}"
    etype: user
    state: present
    permissions: rwx
    default: true
    recursive: true
  no_log: true